meta_product_name: "Muuseek"
meta_title: "Muuseek - Find the perfect music teachers next door"
meta_description: "Muuseek helps you to find the perfect music teachers next to your place"
meta_image: "banner4.jpg" # should exist in `app/assets/images/`
twitter_account: "@Muuseek"   # required for Twitter Cards
